/**
 * Shared context passed to all agents
 */
export interface AgentContext {
  runId: string

  /** Absolute path to the isolated workspace */
  workspace: string

  /** Absolute path to run artifacts */
  artifactRoot: string

  /** Aggregated logs up to the current point */
  logs: string[]

  /** Present only when a step fails (fixer agent) */
  failedStep?: FailedStepContext
}

/**
 * Additional context available when a step fails
 */
export interface FailedStepContext {
  id: string
  label: string

  /** Command that failed */
  command?: string

  /** Exit code from execution */
  exitCode?: number

  /** Raw logs from the failed step */
  logs: string[]

  /** Artifact files generated by this step */
  artifacts?: {
    testResults?: string
    buildOutput?: string
    diff?: string
  }
}

/**
 * Planner output: dynamic workflow steps
 */
export interface PlanStep {
  id: string              // command (npm | pnpm | yarn)
  args: string[]          // command arguments
  label: string
  canFail?: boolean
}


/**
 * Standard agent response envelope
 */
export interface AgentResult<T> {
  success: boolean

  /** Agent output (plans, patches, etc.) */
  output?: T

  /** Failure reason (never thrown) */
  reason?: string
}
