import { writeWorkspaceFile, ensureWorkspace } from "./workspace";
import type { Run } from "../types/run";

interface ScaffoldOptions {
  runId: string;
  template: Run["template"];
}

function joinLines(lines: string[]): string {
  return lines.join("\n");
}

export function scaffoldRealProject({ runId }: ScaffoldOptions) {
  ensureWorkspace(runId);

  const files: Array<{ path: string; content: string }> = [
    {
      path: "package.json",
      content: JSON.stringify(
        {
          name: "autoship-generated-app",
          version: "0.1.0",
          private: true,
          type: "module",
          scripts: {
            dev: "vite",
            build: "tsc && vite build",
            preview: "vite preview",
            lint: "eslint .",
            test: "vitest run --passWithNoTests",
          },
          dependencies: {
            react: "^18.3.1",
            "react-dom": "^18.3.1",
          },
          devDependencies: {
            "@eslint/js": "^9.32.0",
            "@types/react": "^18.3.1",
            "@types/react-dom": "^18.3.1",
            "@testing-library/jest-dom": "^6.6.0",
            "@testing-library/react": "^16.0.0",
            "@vitejs/plugin-react": "^4.2.0",
            eslint: "^9.32.0",
            "eslint-plugin-react-hooks": "^5.2.0",
            "eslint-plugin-react-refresh": "^0.4.20",
            globals: "^15.15.0",
            jsdom: "^20.0.3",
            typescript: "^5.4.5",
            vite: "^5.1.4",
            vitest: "^3.2.4",
            "typescript-eslint": "^8.38.0",
          },
        },
        null,
        2
      ),
    },
    {
      path: "tsconfig.json",
      content: JSON.stringify(
        {
          compilerOptions: {
            target: "ES2020",
            lib: ["DOM", "DOM.Iterable", "ES2020"],
            module: "ESNext",
            moduleResolution: "Bundler",
            jsx: "react-jsx",
            strict: true,
            skipLibCheck: true,
            noEmit: true,
            allowImportingTsExtensions: true,
            isolatedModules: true,
            resolveJsonModule: true,
            useDefineForClassFields: true,
            types: ["vite/client", "vitest/globals"],
          },
          include: ["src"],
          references: [{ path: "tsconfig.node.json" }],
        },
        null,
        2
      ),
    },
    {
      path: "tsconfig.node.json",
      content: JSON.stringify(
        {
          compilerOptions: {
            composite: true,
            module: "ESNext",
            moduleResolution: "Bundler",
            allowSyntheticDefaultImports: true,
          },
          include: ["vite.config.ts"],
        },
        null,
        2
      ),
    },
    {
      path: "vite.config.ts",
      content: joinLines([
        "import { defineConfig } from \"vite\";",
        "import react from \"@vitejs/plugin-react\";",
        "",
        "export default defineConfig({",
        "  plugins: [react()],",
        "  server: {",
        "    host: \"0.0.0.0\",",
        "    port: 4173,",
        "  },",
        "});",
        "",
      ]),
    },
    {
      path: "index.html",
      content: joinLines([
        "<!DOCTYPE html>",
        "<html lang=\"en\">",
        "  <head>",
        "    <meta charset=\"UTF-8\" />",
        "    <link rel=\"icon\" type=\"image/svg+xml\" href=\"/favicon.ico\" />",
        "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />",
        "    <title>AutoShip Generated App</title>",
        "  </head>",
        "  <body>",
        "    <div id=\"root\"></div>",
        "    <script type=\"module\" src=\"/src/main.tsx\"></script>",
        "  </body>",
        "</html>",
        "",
      ]),
    },
    {
      path: "src/main.tsx",
      content: joinLines([
        "import React from \"react\";",
        "import ReactDOM from \"react-dom/client\";",
        "import App from \"./App\";",
        "import \"./main.css\";",
        "",
        "ReactDOM.createRoot(document.getElementById(\"root\")!).render(",
        "  <React.StrictMode>",
        "    <App />",
        "  </React.StrictMode>",
        ");",
        "",
      ]),
    },
    {
      path: "src/App.tsx",
      content: joinLines([
        "import { useMemo, useState } from \"react\";",
        "",
        "type Task = { id: string; title: string; done: boolean };",
        "",
        "export default function App() {",
        "  const [filter, setFilter] = useState<\"active\" | \"completed\">(\"active\");",
        "  const [tasks] = useState<Task[]>([",
        "    { id: \"1\", title: \"Buy milk\", done: false },",
        "    { id: \"2\", title: \"Read book\", done: true },",
        "  ]);",
        "",
        "  const filtered = useMemo(() => {",
        "    /* AUTOShip_TODO_FILTER */",
        "    // Correct filtering logic (will be sabotaged in injectFailure mode)",
        "    if (filter === \"completed\") return tasks.filter((task) => task.done);",
        "    return tasks.filter((task) => !task.done);",
        "    /* END_AUTOShip_TODO_FILTER */",
        "  }, [filter, tasks]);",
        "",
        "  return (",
        "    <div",
        "      style={{",
        "        padding: 24,",
        "        fontFamily: \"'Sora', 'Inter', system-ui, sans-serif\",",
        "        minHeight: \"100vh\",",
        "        background: \"linear-gradient(135deg, #0f172a 0%, #1e293b 50%, #312e81 100%)\",",
        "        color: \"white\",",
        "      }}",
        "    >",
        "      <header style={{ maxWidth: 720, margin: \"0 auto\" }}>",
        "        <h1 style={{ fontSize: \"2.75rem\", marginBottom: 8 }}>AutoShip Todo Demo</h1>",
        "        <p style={{ opacity: 0.85, lineHeight: 1.5 }}>",
        "          Toggle between Active and Completed tasks to validate our autonomous test-fix loop.",
        "        </p>",
        "      </header>",
        "",
        "      <section",
        "        style={{",
        "          maxWidth: 720,",
        "          margin: \"32px auto 0\",",
        "          padding: 24,",
        "          borderRadius: 24,",
        "          background: \"rgba(15, 23, 42, 0.65)\",",
        "          boxShadow: \"0 30px 120px rgba(30, 64, 175, 0.35)\",",
        "          border: \"1px solid rgba(148, 163, 184, 0.18)\",",
        "        }}",
        "      >",
        "        <div style={{ display: \"flex\", gap: 12, marginBottom: 24 }}>",
        "          <button",
        "            style={{",
        "              flex: 1,",
        "              padding: \"0.85rem 1.25rem\",",
        "              borderRadius: 999,",
        "              border: \"none\",",
        "              fontSize: \"1.05rem\",",
        "              cursor: \"pointer\",",
        "              background: filter === \"active\" ? \"#38bdf8\" : \"rgba(148, 163, 184, 0.2)\",",
        "              color: filter === \"active\" ? \"#0f172a\" : \"#e2e8f0\",",
        "              transition: \"all 0.2s ease\",",
        "            }}",
        "            onClick={() => setFilter(\"active\")}",
        "          >",
        "            Active",
        "          </button>",
        "          <button",
        "            style={{",
        "              flex: 1,",
        "              padding: \"0.85rem 1.25rem\",",
        "              borderRadius: 999,",
        "              border: \"none\",",
        "              fontSize: \"1.05rem\",",
        "              cursor: \"pointer\",",
        "              background: filter === \"completed\" ? \"#34d399\" : \"rgba(148, 163, 184, 0.2)\",",
        "              color: filter === \"completed\" ? \"#022c22\" : \"#e2e8f0\",",
        "              transition: \"all 0.2s ease\",",
        "            }}",
        "            onClick={() => setFilter(\"completed\")}",
        "          >",
        "            Completed",
        "          </button>",
        "        </div>",
        "",
        "        <ul style={{ listStyle: \"none\", padding: 0, margin: 0, display: \"grid\", gap: 12 }}>",
        "          {filtered.map((task) => (",
        "            <li",
        "              key={task.id}",
        "              style={{",
        "                display: \"flex\",",
        "                justifyContent: \"space-between\",",
        "                alignItems: \"center\",",
        "                padding: \"1rem 1.25rem\",",
        "                borderRadius: 16,",
        "                background: \"rgba(15, 23, 42, 0.75)\",",
        "                border: \"1px solid rgba(148, 163, 184, 0.16)\",",
        "              }}",
        "            >",
        "              <span style={{ fontSize: \"1.05rem\" }}>{task.title}</span>",
        "              <span role=\"img\" aria-label={task.done ? \"completed\" : \"active\"}>",
        "                {task.done ? \"✅\" : \"🔄\"}",
        "              </span>",
        "            </li>",
        "          ))}",
        "        </ul>",
        "      </section>",
        "    </div>",
        "  );",
        "}",
        "",
      ]),
    },
    {
      path: "src/App.css",
      content: joinLines([
        ":root {",
        "  color-scheme: light dark;",
        "  font-family: \"Inter\", system-ui, sans-serif;",
        "  line-height: 1.5;",
        "  font-weight: 400;",
        "}",
        "",
        "body {",
        "  margin: 0;",
        "}",
        "",
      ]),
    },
    {
      path: "src/main.css",
      content: joinLines([
        ":root {",
        "  font-family: \"Inter\", system-ui, sans-serif;",
        "  line-height: 1.5;",
        "  font-weight: 400;",
        "}",
        "",
        "body {",
        "  margin: 0;",
        "  min-height: 100vh;",
        "}",
        "",
      ]),
    },
    {
      path: "README.md",
      content: joinLines([
        "# AutoShip Generated App",
        "",
        "This project was scaffolded automatically by AutoShip's Day 19-B1 pipeline.",
        "It demonstrates real scaffolding + package installation using pnpm.",
        "",
        "## Available Scripts",
        "- `pnpm dev` — start Vite dev server",
        "- `pnpm build` — type-check + build",
        "- `pnpm test` — run Vitest suite",
        "",
        "Generated on: ${new Date().toISOString()}",
        "",
      ]),
    },
    {
      path: ".gitignore",
      content: joinLines([
        "node_modules/",
        "dist/",
        "build/",
        "*.log",
        "",
      ]),
    },
    {
      path: ".npmrc",
      content: joinLines([
        "shared-workspace-lockfile=false",
        "prefer-workspace-packages=false",
        "",
      ]),
    },
    {
      path: "eslint.config.js",
      content: joinLines([
        "import js from \"@eslint/js\";",
        "import globals from \"globals\";",
        "import reactHooks from \"eslint-plugin-react-hooks\";",
        "import reactRefresh from \"eslint-plugin-react-refresh\";",
        "import tseslint from \"typescript-eslint\";",
        "",
        "export default tseslint.config(",
        "  { ignores: [\"dist\"] },",
        "  {",
        "    extends: [js.configs.recommended, ...tseslint.configs.recommended],",
        "    files: [\"**/*.{ts,tsx}\"],",
        "    languageOptions: {",
        "      ecmaVersion: 2020,",
        "      globals: globals.browser,",
        "    },",
        "    plugins: {",
        "      \"react-hooks\": reactHooks,",
        "      \"react-refresh\": reactRefresh,",
        "    },",
        "    rules: {",
        "      ...reactHooks.configs.recommended.rules,",
        "      \"react-refresh/only-export-components\": [\"warn\", { allowConstantExport: true }],",
        "    },",
        "  }",
        ");",
        "",
      ]),
    },
    {
      path: "src/App.test.tsx",
      content: joinLines([
        "import { describe, it, expect } from \"vitest\";",
        "",
        "describe(\"baseline\", () => {",
        "  it(\"runs tests\", () => {",
        "    expect(true).toBe(true);",
        "  });",
        "});",
        "",
      ]),
    },
  ];

  for (const file of files) {
    writeWorkspaceFile(runId, file.path, file.content);
  }
}
